### ISSUE TITLE
Plugins is broken with latest etherpad version

### ISSUE THREAD

**Issue by Yaco** [marcelklehr/ep_push2delete#6]
Hi! i'am using etherpad git version (rev 5c31d1f)

When i try to use your plugin, the button doesn't work. I get the following error in js console:
~~~
Failed to load 'ep_push2delete/static/js/delete_button.js' for 'ep_push2delete/pushbutton/client_hooks/documentReady': Error: The module at "ep_push2delete/static/js/delete_button.js" does not exist.
~~~

Can you fix this? thanks!

**Comment by Yaco** [comment]
Here is the fix: https://github.com/marcelklehr/ep_push2delete/pull/7

**Comment by marcelklehr** [comment]
Thanks for reporting :)
