### ISSUE TITLE
Can't load push2delete

### ISSUE THREAD

**Issue by bsteindorf** [marcelklehr/ep_push2delete#9]
Hi,

it seems, that the actuall version of etherpad can't load push2delte:
"Failed to load 'ep_push2delete/static/js/delete_button' for 'ep_push2delete/pushbutton/client_hooks/documentReady': Error: The module at "ep_etherpad-lite/static/js/pad_modals.js" does not exist."

On Button press i got:
TypeError: $(...).closest(...).get(...) is undefined
Syntax-Error

Etherpad is a fresh 'git pull'

Thank and regards,
Benedikt

**Comment by marcelklehr** [comment]
thanks for reporting, should be fixed now :)

**Comment by stndrf** [comment]
thanks for fixing, i can confirm it's working now

**Comment by marcelklehr** [comment]
great! :)
